from enum import StrEnum


class NotificationType(StrEnum):

    MESSAGE_RECEIVED = "MESSAGE_RECEIVED"

    OFFER_RECEIVED = "OFFER_RECEIVED"
    COUNTER_OFFER = "COUNTER_OFFER"
    OFFER_ACCEPTED = "OFFER_ACCEPTED"
    OFFER_REJECTED = "OFFER_REJECTED"

    TRANSACTION_COMPLETED = (
        "TRANSACTION_COMPLETED"
    )

    LISTING_PUBLISHED = "LISTING_PUBLISHED"
    LISTING_EXPIRING = "LISTING_EXPIRING"
    LISTING_EXPIRED = "LISTING_EXPIRED"
    LISTING_SUSPENDED = "LISTING_SUSPENDED"

    PAYMENT_CONFIRMED = "PAYMENT_CONFIRMED"
    PAYMENT_FAILED = "PAYMENT_FAILED"

    VERIFICATION_APPROVED = (
        "VERIFICATION_APPROVED"
    )

    VERIFICATION_REJECTED = (
        "VERIFICATION_REJECTED"
    )

    ACCOUNT_SUSPENDED = "ACCOUNT_SUSPENDED"